# Generated by Django 2.1.7 on 2019-04-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifacts',
            fields=[
                ('session_id', models.IntegerField()),
                ('artifact_id', models.AutoField(primary_key=True, serialize=False)),
                ('artifact_url', models.CharField(max_length=255)),
                ('retrieval_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
