# Generated by Django 2.1.7 on 2019-04-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCriteria',
            fields=[
                ('criterion_id', models.AutoField(primary_key=True, serialize=False)),
                ('criterion', models.CharField(max_length=255)),
            ],
        ),
    ]
